export { default as reducer } from '../redux/reducer';
export { default as route } from '../route';
export { default as projectExplorer } from './projectExplorer';
export { default as form } from './form';
export { default as tab } from './tab';
export { default as app } from './app';
export { default as menu } from './menu';
export { default as view } from './view';
export { default as colors } from '../colors';
export { default as icons } from './icons';
export { default as dashboard } from './dashboard';
export const name = 'cra';