export const PTY_CLEAR_OUTPUT = 'PTY_CLEAR_OUTPUT';
export const PTY_NPM_LIST_BEGIN = 'PTY_NPM_LIST_BEGIN';
export const PTY_NPM_LIST_SUCCESS = 'PTY_NPM_LIST_SUCCESS';
export const PTY_NPM_LIST_FAILURE = 'PTY_NPM_LIST_FAILURE';
export const PTY_NPM_LIST_DISMISS_ERROR = 'PTY_NPM_LIST_DISMISS_ERROR';
export const PTY_REMOVE_OUTPUT_FROM_STORE = 'PTY_REMOVE_OUTPUT_FROM_STORE';
