export default {
  features: 'rekit',
  feature: 'book',
  'initial-state': 'database',
  component: 'appstore-o',
  components: 'appstore-o',
  'folder-alias': 'folder',
  folder: 'folder',
  others: 'folder',
  file: 'file',
  route: 'sharealt',
  routes: 'sharealt',
  actions: 'notification',
  action: 'notification',
};
