export const PLUGIN_TEST_LIST_ALL_TEST = 'PLUGIN_TEST_LIST_ALL_TEST';
export const PLUGIN_TEST_CLEAR_TEST_LIST = 'PLUGIN_TEST_CLEAR_TEST_LIST';
export const PLUGIN_TEST_REMOVE_TEST_FROM_LIST = 'PLUGIN_TEST_REMOVE_TEST_FROM_LIST';
