export const PLUGIN_TEST_LIST_ALL_TEST = 'PLUGIN_TEST_LIST_ALL_TEST';
export const PLUGIN_TEST_CLEAR_TEST_LIST = 'PLUGIN_TEST_CLEAR_TEST_LIST';
export const PLUGIN_TEST_REMOVE_TEST_FROM_LIST = 'PLUGIN_TEST_REMOVE_TEST_FROM_LIST';
export const PLUGIN_TEST_RUN_TEST_BEGIN = 'PLUGIN_TEST_RUN_TEST_BEGIN';
export const PLUGIN_TEST_RUN_TEST_SUCCESS = 'PLUGIN_TEST_RUN_TEST_SUCCESS';
export const PLUGIN_TEST_RUN_TEST_FAILURE = 'PLUGIN_TEST_RUN_TEST_FAILURE';
export const PLUGIN_TEST_RUN_TEST_DISMISS_ERROR = 'PLUGIN_TEST_RUN_TEST_DISMISS_ERROR';
export const PLUGIN_TEST_SELECT_TEST = 'PLUGIN_TEST_SELECT_TEST';
